name: CI Build

on:
  workflow_dispatch:
    inputs:
      version:  
        description: 'Version'
        required: true
        type: 'string'
      release_notes:
        description: 'Release Notes'
        required: true
        type: 'string'

permissions:
  contents: write

jobs:
  cross-compile:
    strategy:
      matrix:
        platform:
          - name: Linux_x64
            exe_target: x86_64-linux-gnu
            lib_target: x86_64-linux-musl
            image: ubuntu-latest
          - name: Linux_x86
            exe_target: x86-linux-gnu
            lib_target: x86-linux-musl
            image: ubuntu-latest
          - name: Linux_ARM64
            exe_target: aarch64-linux-gnu
            lib_target: aarch64-linux-musl
            image: ubuntu-24.04-arm
          - name: macOS_x64
            exe_target: x86_64-macos
            lib_target: x86_64-macos
            image: macos-latest
          - name: macOS_ARM64
            exe_target: aarch64-macos
            lib_target: aarch64-macos
            image: macos-latest
          - name: Windows_x64
            exe_target: x86_64-windows-gnu
            lib_target: x86_64-windows-gnu
            image: ubuntu-latest
          - name: Windows_x86
            exe_target: x86-windows-gnu
            lib_target: x86-windows-gnu
            image: ubuntu-latest
          - name: Windows_ARM64
            exe_target: aarch64-windows-gnu
            lib_target: aarch64-windows-gnu
            image: ubuntu-latest
          - name: Android_ARM64
            exe_target: ''
            lib_target: aarch64-linux-android
            image: ubuntu-latest
          - name: iOS_ARM64
            exe_target: ''
            lib_target: aarch64-ios
            image: macos-latest
          
    runs-on: ${{ matrix.platform.image }}
    steps:
      - name: Check out
        uses: actions/checkout@v7
      - name: Setup zig cc
        uses: mlugg/setup-zig@v2
        if: ${{ (matrix.platform.name != 'Android_ARM64') && (matrix.platform.name != 'iOS_ARM64') }}
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.6.0
        id: setup-ndk
        if: ${{ matrix.platform.lib_target == 'aarch64-linux-android' }}
        with:
          ndk-version: r27d
      - name: Compile lib for ${{ matrix.platform.name }}
        run: make lib
        env:
          TARGET: ${{ matrix.platform.lib_target }}
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Compile exe for ${{ matrix.platform.name }}
        if: ${{ matrix.platform.exe_target != '' }}
        run: rm -rf build && make
        env:
          TARGET: ${{ matrix.platform.exe_target }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ptexconv_${{ matrix.platform.name }}
          path: ptexconv*
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: [ cross-compile ]
    steps:
      - name: Check out
        uses: actions/checkout@v7

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: ptexconv_*

      - name: Create release packages
        run: |
          mkdir -p release/libs/include
          mkdir -p release/libs/lib
          mkdir -p release/ptexconv-Linux-arm64
          mkdir -p release/ptexconv-Linux-x64
          mkdir -p release/ptexconv-Linux-x86
          mkdir -p release/ptexconv-macOS-arm64
          mkdir -p release/ptexconv-macOS-x64
          mkdir -p release/ptexconv-Windows-arm64
          mkdir -p release/ptexconv-Windows-x64
          mkdir -p release/ptexconv-Windows-x86

          mv src/*.h release/libs/include/
          mv ptexconv_Linux_ARM64/ptexconv.so release/libs/lib/ptexconv_aarch64.so
          mv ptexconv_Linux_x64/ptexconv.so release/libs/lib/ptexconv_x86_64.so
          mv ptexconv_Linux_x86/ptexconv.so release/libs/lib/ptexconv_x86.so
          mv ptexconv_macOS_ARM64/ptexconv.dylib release/libs/lib/ptexconv_aarch64.dylib
          mv ptexconv_macOS_x64/ptexconv.dylib release/libs/lib/ptexconv_x86_64.dylib
          mv ptexconv_Windows_ARM64/ptexconv.dll release/libs/lib/ptexconv_aarch64.dll
          mv ptexconv_Windows_x64/ptexconv.dll release/libs/lib/ptexconv_x86_64.dll
          mv ptexconv_Windows_x86/ptexconv.dll release/libs/lib/ptexconv_x86.dll
          mv ptexconv_Android_ARM64/ptexconv.so release/libs/lib/ptexconv_android_aarch64.so
          mv ptexconv_iOS_ARM64/ptexconv.dylib release/libs/lib/ptexconv_ios_aarch64.dylib

          mv ptexconv_Linux_ARM64/ptexconv release/ptexconv-Linux-arm64/
          mv ptexconv_Linux_x64/ptexconv release/ptexconv-Linux-x64/
          mv ptexconv_Linux_x86/ptexconv release/ptexconv-Linux-x86/
          mv ptexconv_macOS_ARM64/ptexconv release/ptexconv-macOS-arm64/
          mv ptexconv_macOS_x64/ptexconv release/ptexconv-macOS-x64/
          mv ptexconv_Windows_ARM64/ptexconv.exe release/ptexconv-Windows-arm64/
          mv ptexconv_Windows_x64/ptexconv.exe release/ptexconv-Windows-x64/
          mv ptexconv_Windows_x86/ptexconv.exe release/ptexconv-Windows-x86/

          for dir in release/*; do
            zip $dir.zip $dir/*
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          name: ptexconv ${{ inputs.version }}
          tag_name: v${{ inputs.version }}
          generate_release_notes: true
          files: ./release/*
          body: ${{ inputs.release_notes }}